#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const CSS_DIR = "production/css";
const OUTPUT_FILE = "production/style.css";

// CSS files in the correct import order
const CSS_FILES = [
  "_colors.css",
  "_fonts.css",
  "_animations.css",
  "_freezebox.css",
  "globals.css",
  "header.css",
  "breadcrumbs.css",
  "auth.css",
  "catalog.css",
  "course-info.css",
  "learning-path-info.css",
  "courses-learning-paths.css",
  "lessons.css",
  "404.css",
  "footer.css",
  "completion.css",
];

// Additional CSS that goes at the end (from current style.css)
const ADDITIONAL_CSS = `
.focus-link-v2::before,
.course-text-content a::before,
#profile-course-table td > a::before,
.filter-group-title::before,
.alert-box a::before {
  pointer-events: none;
}

#cp-content::before,
#cp-content::after,
.row.dp-row-flex-v2::before,
.row.dp-row-flex-v2::after {
  content: none;
}

.bullet .fa.fa-check-circle {
  color: var(--blurple);
}
.lp-footer {
  position: relative;
}

.related-parent-objects {
  /* Hide the "Also available as part of" section for Learning Paths */
  display: none !important;
}

.sj-save-toggle-block {
  /* Hide the new save course/learning path feature */
  display: none !important;
}
`;

let compiledCSS = "/* Compiled CSS - DO NOT EDIT DIRECTLY */\n";
compiledCSS += "/* This file is generated by build-css.mjs */\n\n";

// Concatenate all CSS files
for (const file of CSS_FILES) {
  const filePath = join(CSS_DIR, file);
  try {
    const content = readFileSync(filePath, "utf8");
    compiledCSS += `/* ${file} */\n`;
    compiledCSS += content.trim() + "\n\n";
  } catch (error) {
    console.error(`✗ Failed to read ${file}: ${error.message}`);
    process.exit(1);
  }
}

// Add additional CSS
compiledCSS += "/* Additional styles */\n";
compiledCSS += ADDITIONAL_CSS.trim() + "\n";

// Write the compiled CSS
try {
  writeFileSync(OUTPUT_FILE, compiledCSS, "utf8");
  console.log(`✓ CSS compiled to ${OUTPUT_FILE}`);
} catch (error) {
  console.error(`✗ Failed to write ${OUTPUT_FILE}: ${error.message}`);
  process.exit(1);
}
