name: Sync to PROD GCS

on:
  push:
    branches:
      - main
    paths:
      - 'production/**'
      - 'fonts/**'
  workflow_dispatch:

permissions: {}

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: 'Github Actions Runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Authenticate to Google Cloud
        id: auth
        uses: step-security/google-github-auth@57c51210cb4d85d8a5d39dc4c576c79bd693f914 # v3.0.1
        with:
          service_account: "github-chainguard-academy@chainguard-academy.iam.gserviceaccount.com"
          workload_identity_provider: "projects/456977358484/locations/global/workloadIdentityPools/chainguard-academy/providers/chainguard-edu"

      - name: Setup G Cloud SDK
        uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' # v2.0.11

      - name: Sync production directory to GCS
        run: |
          gsutil -m rsync -r -d production/ gs://chainguard-courses-theme/production/

      - name: Sync fonts directory to GCS
        run: |
          gsutil -m rsync -r -d fonts/ gs://chainguard-courses-theme/fonts/
